#이하공통
mybatis:
   type-aliases-package: com.danbplus.example.mybatis
   mapper-locations: /mapper/mybatis/*.xml
   
spring:
  thymeleaf:
     cache: false
     prefix: classpath:/templates/
     suffix: .html
     #view-names: thymeleaf/*  
  
  jpa:
    show-sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy : org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
      
  devtools: 
   livereload: 
     enabled: false
        
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://dev.danbplus.com:53306/danbplusSTS_SHJ?UTC&allowPublickeyRetrieval=true
    username: danbplus
    password: Danb1235!!
